### ISSUE TITLE
Sound error

### ISSUE THREAD

**Issue by enriquesomolinos** [enriquesomolinos/REminiscence-Vita#1]
Sounds aren't reproduced correctly.

**Comment by enriquesomolinos** [comment]
It only occurs in cutscenes.

**Comment by JonnyMnemonic** [comment]
I tried this mod http://cmikavac.net/2011/09/25/making-sound-files-for-reminiscence-flashback-work/
music appeared in cutscenes, but its too fast

**Comment by enriquesomolinos** [comment]
Thanks for the information!

**Comment by melchieor** [comment]
I loaded the sound files including the Sega cd speech files but the music plays too fast and the speech makes the program crash. I am using ver. 40.

**Comment by enriquesomolinos** [comment]
I close this issue because is ambigous. I open i new issue with the cutscenes error
